- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hello! Strengthening the fundamentals of DevOps with AWS through practice and hands-on learning in a 120-hour course, guided by Trainer Siva."