- name: variables to print
  hosts: web
  vars: #play level, all tasks in this play have access to this
    COURSE: "DevOps with AWS from PLAY level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar"
  # vars_files:
  # - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential
  tasks:
  - name: print the information
    vars:
      # COURSE: "DevOps with AWS from TASK level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar"
    ansible.builtin.debug:
      msg: "Hello! Strengthening the fundamentals of {{COURSE}}"

#1 first preference is always command line/args
#2 Task level
#3 Files