- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exits or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that gets output from above command
    ignore_errors: true

  - name: prin the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"

  - name: create user
    anisble.builtin.command: id expense
    when: USER.rc != 0